ui: mocha-tdd
browserify:
  - transform: es2020
browsers:
  - name: firefox
    version: -1..latest
  - name: chrome
    varsion: -1..latest
  - name: safari
    version: -1..latest
  - name: microsoftedge
    version: -1..latest
