ui: mocha-tdd
browserify:
  - transform: es2020
browsers:
  - name: firefox
    version: -1..latest
  - name: chrome
    version: -1..latest
  - name: safari
    version: -1..latest
  - name: microsoftedge
    version: -1..latest
  - name: internet explorer
    version: latest
concurrency: 4
tunnel:
  type: ngrok
  bind_tls: true
